export enum StateActions {
  LOADING = "LOADING",
  SELECTED_LIST = "SELECTED_LIST",
  SET_CATEGORIES = "SET_CATEGORIES",
  SELECT_CATEGORY = "SELECT_CATEGORY",
  SET_POSTS = "SET_POSTS",
  SEARCH_POSTS = "SEARCH_POSTS",
  ERROR = "ERROR",
  ERROR_POSTS = "ERROR_POSTS"
}
